package hu.dojcsak.openrewrite.recipe.jee.ejb;

import lombok.EqualsAndHashCode;
import lombok.Value;
import org.openrewrite.ExecutionContext;
import org.openrewrite.Recipe;
import org.openrewrite.TreeVisitor;
import org.openrewrite.java.AnnotationMatcher;
import org.openrewrite.java.JavaIsoVisitor;
import org.openrewrite.java.JavaParser;
import org.openrewrite.java.JavaTemplate;
import org.openrewrite.java.tree.J;
import org.openrewrite.java.tree.JContainer;
import org.openrewrite.java.tree.JLeftPadded;
import org.openrewrite.java.tree.TypeTree;

import java.util.Comparator;

/**
 * Adds {@code @Transactional} to Spring {@code @Service} classes that do not already have it,
 * as a replacement for EJB Container-Managed Transactions (CMT).
 * EJBs have CMT enabled by default; the equivalent in Spring is explicit {@code @Transactional}.
 */
@Value
@EqualsAndHashCode(callSuper = false)
public class AddTransactionalToServiceBeans extends Recipe {

    String displayName = "Add @Transactional to @Service beans";

    String description = "Adds @Transactional to Spring @Service classes that do not already have it, " +
            "as a replacement for EJB Container-Managed Transactions (CMT).";

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        return new JavaIsoVisitor<ExecutionContext>() {
            private final AnnotationMatcher serviceMatcher =
                    new AnnotationMatcher("@org.springframework.stereotype.Service");
            private final AnnotationMatcher transactionalMatcher =
                    new AnnotationMatcher("@org.springframework.transaction.annotation.Transactional");

            @Override
            public J.ClassDeclaration visitClassDeclaration(
                    J.ClassDeclaration classDecl, ExecutionContext ctx) {
                J.ClassDeclaration cd = super.visitClassDeclaration(classDecl, ctx);

                if (cd.getLeadingAnnotations().stream().noneMatch(serviceMatcher::matches)) {
                    return cd;
                }
                if (cd.getLeadingAnnotations().stream().anyMatch(transactionalMatcher::matches)) {
                    return cd;
                }

                // JavaTemplate.apply()'s default autoFormat pass can reflow the class declaration's
                // extends/implements clauses (e.g. collapsing a manually-indented multi-line layout,
                // as generated by Andromda, onto a single unindented line) even though only a leading
                // annotation is being inserted here - restore them verbatim afterward, since this
                // recipe never intends to touch that formatting.
                JLeftPadded<TypeTree> extendsBeforeTemplate = cd.getPadding().getExtends();
                JContainer<TypeTree> implementsBeforeTemplate = cd.getPadding().getImplements();
                cd = JavaTemplate.builder("@Transactional")
                        .imports("org.springframework.transaction.annotation.Transactional")
                        .javaParser(JavaParser.fromJavaVersion().classpathFromResources(ctx, "spring-tx"))
                        .build()
                        .apply(getCursor(), cd.getCoordinates().addAnnotation(
                                Comparator.comparing(J.Annotation::getSimpleName)));
                if (extendsBeforeTemplate != null) {
                    cd = cd.getPadding().withExtends(extendsBeforeTemplate);
                }
                if (implementsBeforeTemplate != null) {
                    cd = cd.getPadding().withImplements(implementsBeforeTemplate);
                }
                maybeAddImport("org.springframework.transaction.annotation.Transactional", false);

                return cd;
            }
        };
    }
}
